[package]
name = "invoicetoexcel"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
lopdf = "0.34.0"
pdf-extract = "0.7.10"
regex = "1.11.1"
rocket = "0.5.1"
rust_xlsxwriter = "0.79.4"
tokio = "1.42.0"
